// import './console';
import './assets/fontawesome/css/all.css';
import './fonts.css';
import './style.css';
import './js/pages/app';
import * as Preact from 'preact';
import * as PreactHooks from 'preact/hooks';
window.Preact = Preact;
window.PreactHooks = PreactHooks;
window.h = Preact.h;
